// The weekly live-only backtest: what the paper ledger earned on the boards we
// actually had at the time, how the two prices compare on those same boards, and
// how much of any of it is more than noise.
//
// Live means the Tuesday, Thursday and Saturday captures. A backfilled board
// (opening, closing) is a reconstruction with hindsight in it and is excluded by
// slot; see lib/backtest-live.mjs for why, and for why most of what remains is
// still noise.
//
// Sections:
//   1. BOARDS        what each live capture contained, and under which price
//   2. PRICING       Brier of the book, the projection and the pool on live boards
//   3. BETS          the Firehose (every edge >= the minimum, 1u, best price), by
//                    week and slot, with the ROI band and CLV
//   4. COUNTERFACTUAL the same live boards re-priced under the OTHER model and
//                    run through the same persona engine
//   5. PERSONAS      every persona, live only
//   6. CAN YOU READ IT? how many bets it takes to see an effect of that size
//
// Usage:
//   npm run backtest-live
//   node scripts/backtest-live.mjs [--season 2026] [--min-edge 0.03]
//                                  [--live-slots main,thursday,saturday]
//                                  [--no-counterfactual]
//                                  [--write]   data/backtest/{season}/live.md + .json
//                                  [--json]
//
// Reads the ledgers in data/bets/ (regenerated by simulate-personas.mjs, so run
// that first if the actuals are new) and the captures in data/props/.

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, symlinkSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { readCsv, toCsv } from "./lib/csv.mjs";
import { loadSeason, availableSeasons, isPointInTime, isProjectionPrice, readPropRow } from "./lib/pricing-dataset.mjs";
import { slotDir } from "./lib/slots.mjs";
import { PERSONAS } from "./lib/personas.mjs";
import { median, sigmoid } from "./lib/consensus.mjs";
import { isBettableStat } from "./lib/markets.mjs";
import { buildSourceModel, outcomeFrom } from "./lib/source-model.mjs";
import { bookVotes, poolVotes, shareFor, weightsForStat } from "./lib/source-weights.mjs";
import { PROPS_COLUMNS, repriceWithPool } from "./capture-props.mjs";
import {
  LIVE_SLOTS,
  isLiveSlot,
  summarizeBets,
  betsToResolve,
  verdict,
  boardStats,
  pricingAccuracy,
  counterfactualOf,
  projectionProbOf,
  asProjectionPriced,
  MIN_BETS_FOR_A_VERDICT,
  MIN_CLV_FOR_A_BOOK,
  indexClosingConsensus,
  summarizeByBook,
} from "./lib/backtest-live.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const pad2 = (n) => String(n).padStart(2, "0");

function parseArgs(argv) {
  const a = { season: null, dataDir: "data", minEdge: 0.03, liveSlots: LIVE_SLOTS, counterfactual: true, write: false, json: false };
  for (let i = 0; i < argv.length; i++) {
    const next = () => argv[++i];
    switch (argv[i]) {
      case "--season": a.season = Number(next()); break;
      case "--data-dir": a.dataDir = next(); break;
      case "--min-edge": a.minEdge = Number(next()); break;
      case "--live-slots": a.liveSlots = next().split(",").map((s) => s.trim()).filter(Boolean); break;
      case "--no-counterfactual": a.counterfactual = false; break;
      case "--write": a.write = true; break;
      case "--json": a.json = true; break;
      case "-h":
      case "--help":
        console.log("Usage: node scripts/backtest-live.mjs [--season Y] [--min-edge 0.03] [--live-slots a,b] [--no-counterfactual] [--write] [--json]");
        process.exit(0);
        break;
      default:
        throw new Error(`Unknown argument: ${argv[i]}`);
    }
  }
  if (!(a.minEdge >= 0)) throw new Error("--min-edge must be >= 0");
  return a;
}

// ---------------------------------------------------------------------------
// Formatting
// ---------------------------------------------------------------------------

const pct = (x, d = 1) => (x === null || x === undefined || !Number.isFinite(x) ? "–" : `${x >= 0 ? "+" : ""}${(100 * x).toFixed(d)}%`);
const fx = (x, d = 4) => (x === null || x === undefined || !Number.isFinite(x) ? "–" : `${x >= 0 ? "+" : ""}${x.toFixed(d)}`);
const roiCell = (s) => (s.settled === 0 ? "–" : `${pct(s.roi)} ±${s.roiBand === null ? "?" : (100 * s.roiBand).toFixed(0)}%`);
const clvCell = (s) =>
  s.clv.nMatched === 0 ? "–" : `${(100 * s.clv.beatRate).toFixed(0)}% of ${s.clv.nMatched}, ${s.clv.avgClvProb >= 0 ? "+" : ""}${(100 * s.clv.avgClvProb).toFixed(1)} pts`;
const pendingCell = (s) => `${s.unplayed}${s.noLine ? ` + ${s.noLine} no line` : ""}${s.noSource ? ` + ${s.noSource} ungradable` : ""}`;

function table(headers, rows) {
  const line = (cells) => `| ${cells.join(" | ")} |`;
  return [line(headers), line(headers.map(() => "---")), ...rows.map(line)].join("\n");
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

function weekFiles(dir) {
  return existsSync(dir)
    ? readdirSync(dir)
        .map((f) => f.match(/^week-(\d+)\.csv$/))
        .filter(Boolean)
        .map((m) => Number(m[1]))
        .sort((x, y) => x - y)
    : [];
}

function loadLedger(dataDir, persona, season) {
  const dir = join(ROOT, dataDir, "bets", persona, String(season));
  return weekFiles(dir).flatMap((w) => readCsv(join(dir, `week-${pad2(w)}.csv`)));
}

// Every live capture's props file: { slot, week, path }.
function liveBoards(dataDir, season, liveSlots) {
  const base = join(ROOT, dataDir, "props", String(season));
  const out = [];
  for (const slot of liveSlots) {
    const dir = join(base, slotDir(slot));
    for (const week of weekFiles(dir)) out.push({ slot, week, path: join(dir, `week-${pad2(week)}.csv`) });
  }
  return out.sort((x, y) => x.week - y.week || x.slot.localeCompare(y.slot));
}

// ---------------------------------------------------------------------------
// Pricing accuracy on live boards
// ---------------------------------------------------------------------------

function liveSamples(quotes, actualsByWeek, model, liveSlots) {
  const groups = new Map();
  for (const q of quotes) {
    if (!isLiveSlot(q.slot, liveSlots) || !isPointInTime(q) || !isBettableStat(q.stat)) continue;
    const key = [q.slot, q.week, q.playerId, q.stat, q.line].join("|");
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(q);
  }
  const out = [];
  for (const rows of groups.values()) {
    const first = rows[0];
    const y = outcomeFrom(actualsByWeek, first);
    if (y === null) continue;
    const votes = bookVotes(rows, { assumedHold: model.holdByStat.get(first.stat) });
    if (votes.length < 3) continue;
    const m = model.at(first.week);
    const withProj = rows.find(isProjectionPrice);
    const pProj = withProj ? withProj.probOver : NaN;
    const pool = poolVotes(votes, {
      weights: weightsForStat(m, first.stat),
      projectionProb: Number.isFinite(pProj) ? pProj : null,
      projectionShare: shareFor(m.shares, first.stat, first.slot),
    });
    out.push({
      week: first.week,
      slot: first.slot,
      y,
      pBook: sigmoid(median(votes.map((v) => v.logit))),
      pProj,
      pPool: pool.prob,
      cluster: `${first.week}|${first.playerId}`,
    });
  }
  return out;
}

// ---------------------------------------------------------------------------
// The counterfactual
// ---------------------------------------------------------------------------

// Re-price a props file's rows under the pool, as it would have stood that week.
function asPoolPriced(rows, model, slot) {
  const cand = rows.map((r) => {
    const proj = projectionProbOf(r);
    return {
      r,
      rotowirePlayerId: r.PlayerID,
      statKey: r.Stat,
      line: Number(r.Line),
      side: r.Side || "over",
      sportsbook: r.Book,
      odds: Number(r.Odds),
      oppositeOdds: r.OppositeOdds === "" || r.OppositeOdds === undefined ? null : Number(r.OppositeOdds),
      impliedProb: Number(r.ImpliedProb),
      fairProb: Number(r.FairProb),
      hold: r.Hold === "" || r.Hold === undefined ? null : Number(r.Hold),
      // The pool takes the projection's own probability as its input.
      ourProb: proj ?? Number(r.OurProb),
      projProb: proj ?? Number(r.OurProb),
      edge: Number(r.Edge),
      modelEdge: Number(r.ModelEdge),
    };
  });
  repriceWithPool(cand, model, { slot });
  return cand.map((c) => ({
    ...c.r,
    OurProb: c.ourProb.toFixed(4),
    ProjProb: c.projProb.toFixed(4),
    Edge: c.edge.toFixed(4),
    ModelEdge: c.modelEdge.toFixed(4),
    PriceModel: c.priceModel ?? c.r.PriceModel ?? "projection",
  }));
}

// Run the Firehose over the live boards re-priced under the other model, in a
// throwaway data directory so nothing in data/ is touched, and return its ledger.
function runCounterfactual(a, season, boards, model) {
  const tmp = mkdtempSync(join(tmpdir(), "backtest-live-"));
  try {
    for (const d of ["actuals", "closing", "projections", "players"]) {
      if (existsSync(join(ROOT, a.dataDir, d))) symlinkSync(join(ROOT, a.dataDir, d), join(tmp, d));
    }
    const used = [];
    for (const b of boards) {
      const rows = readCsv(b.path);
      const major = Object.entries(boardStats(rows).priceModels).sort((x, y) => y[1] - x[1])[0]?.[0] ?? "projection";
      const alt = counterfactualOf(major);
      const repriced = alt === "projection" ? rows.map(asProjectionPriced).filter(Boolean) : asPoolPriced(rows, model.at(b.week), b.slot);
      used.push({ week: b.week, slot: b.slot, asCaptured: major, counterfactual: alt });

      const dir = slotDir(b.slot);
      const edges = repriced.filter((r) => (r.Bettable === undefined || r.Bettable === "" || Number(r.Bettable) === 1) && Number(r.Edge) >= a.minEdge);
      for (const [kind, set] of [["props", repriced], ["edges", edges]]) {
        const d = join(tmp, kind, String(season), dir);
        mkdirSync(d, { recursive: true });
        writeFileSync(join(d, `week-${pad2(b.week)}.csv`), toCsv(PROPS_COLUMNS, set));
      }
    }
    const rel = relative(ROOT, tmp);
    const r = spawnSync(process.execPath, [join(__dirname, "simulate-personas.mjs"), "--data-dir", rel, "--persona", "firehose", "--season", String(season)], { encoding: "utf8" });
    if (r.status !== 0) throw new Error(`counterfactual replay failed: ${r.stderr || r.stdout}`);
    return { rows: loadLedger(rel, "firehose", season), used };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------

function main() {
  const a = parseArgs(process.argv.slice(2));
  const seasons = availableSeasons(join(ROOT, a.dataDir));
  const season = a.season ?? seasons[seasons.length - 1];
  if (!season) throw new Error(`No prop captures under ${a.dataDir}/props/`);

  const boards = liveBoards(a.dataDir, season, a.liveSlots);
  const live = (rows) => rows.filter((r) => isLiveSlot(r.Slot, a.liveSlots));
  const firehose = live(loadLedger(a.dataDir, "firehose", season));
  const latestWeek = Math.max(0, ...boards.map((b) => b.week), ...firehose.map((r) => Number(r.Week)));
  // A week is complete once a later week has been captured and its actuals exist.
  const completeWeeks = new Set(
    weekFiles(join(ROOT, a.dataDir, "actuals", String(season))).filter((w) => w < latestWeek)
  );

  // 1. Boards
  const boardRows = boards.map((b) => ({ ...b, stats: boardStats(readCsv(b.path), { minEdge: a.minEdge }) }));

  // 2. Pricing accuracy on live boards
  const { quotes, actualsByWeek } = loadSeason(season, { dataDir: join(ROOT, a.dataDir) });
  const model = buildSourceModel(quotes, actualsByWeek);
  const samples = liveSamples(quotes, actualsByWeek, model, a.liveSlots);
  const accWeeks = [...new Set(samples.map((s) => s.week))].sort((x, y) => x - y);
  const accuracy = { overall: pricingAccuracy(samples), byWeek: Object.fromEntries(accWeeks.map((w) => [w, pricingAccuracy(samples.filter((s) => s.week === w))])) };

  // 3. Bets
  const weekSlots = [...new Set(firehose.map((r) => `${r.Week}|${r.Slot || "main"}`))].sort((x, y) => Number(x.split("|")[0]) - Number(y.split("|")[0]) || x.localeCompare(y));
  const betsByWeek = weekSlots.map((k) => {
    const [w, slot] = k.split("|");
    const rows = firehose.filter((r) => String(r.Week) === w && (r.Slot || "main") === slot);
    const board = boardRows.find((b) => String(b.week) === w && b.slot === slot);
    return { week: Number(w), slot, models: [...new Set(rows.map((r) => r.PriceModel || "projection"))].join("+"), edgeRows: board?.stats.edges ?? null, summary: summarizeBets(rows, { completeWeeks }) };
  });
  const total = summarizeBets(firehose, { completeWeeks });
  const byModel = Object.fromEntries(
    [...new Set(firehose.map((r) => r.PriceModel || "projection"))].map((m) => [m, summarizeBets(firehose.filter((r) => (r.PriceModel || "projection") === m), { completeWeeks })])
  );

  // 3b. CLV by book. The closing prices are the live daily closing captures in
  // data/closing/, which is a different file from the backfilled closing board.
  const closingDir = join(ROOT, a.dataDir, "closing", String(season));
  const closingQuotes = weekFiles(closingDir).flatMap((w) =>
    readCsv(join(closingDir, `week-${pad2(w)}.csv`)).map((row) => readPropRow(row, "closing")).filter(Boolean)
  );
  const closingIndex = indexClosingConsensus(closingQuotes, { holdByStat: model.holdByStat });
  const byBook = summarizeByBook(firehose, { completeWeeks, closingIndex });

  // 4. Counterfactual
  let cf = null;
  if (a.counterfactual && boards.length > 0) {
    const { rows, used } = runCounterfactual(a, season, boards, model);
    const cfLive = live(rows);
    // Two different questions, kept apart: boards captured on the projection price
    // re-priced with the pool, and boards captured on the pool re-priced with the
    // projection. Summing them would mix a week-1 Tuesday drop with a Thursday one.
    const directions = {};
    for (const dir of ["pool", "projection"]) {
      const boardsD = used.filter((u) => u.counterfactual === dir);
      if (boardsD.length === 0) continue;
      const inD = (row) => boardsD.some((u) => u.week === Number(row.Week) && u.slot === (row.Slot || "main"));
      directions[dir] = {
        boards: boardsD.map((u) => `week ${u.week} ${u.slot}`),
        asCaptured: summarizeBets(firehose.filter(inD), { completeWeeks }),
        other: summarizeBets(cfLive.filter(inD), { completeWeeks }),
      };
    }
    cf = { used, directions };
  }

  // 5. Personas
  const personas = PERSONAS.map((p) => ({ id: p.id, label: p.label, summary: summarizeBets(live(loadLedger(a.dataDir, p.id, season)), { completeWeeks }) }));

  const result = { season, minEdge: a.minEdge, liveSlots: a.liveSlots, latestWeek, completeWeeks: [...completeWeeks], boards: boardRows, accuracy, betsByWeek, total, byModel, byBook, counterfactual: cf, personas };
  const markdown = render(result);

  if (a.json) console.log(JSON.stringify(result, null, 2));
  else console.log(markdown);

  if (a.write) {
    const dir = join(ROOT, a.dataDir, "backtest", String(season));
    mkdirSync(dir, { recursive: true });
    writeIfChanged(join(dir, "live.md"), markdown + "\n");
    writeIfChanged(join(dir, "live.json"), JSON.stringify(result, null, 2) + "\n");
    if (!a.json) console.log(`\nWrote ${join(a.dataDir, "backtest", String(season))}/live.md and live.json`);
  }
}

function writeIfChanged(path, text) {
  if (existsSync(path) && readFileSync(path, "utf8") === text) return;
  writeFileSync(path, text);
}

// ---------------------------------------------------------------------------
// The report
// ---------------------------------------------------------------------------

function render(r) {
  const out = [];
  out.push(`# Live backtest — ${r.season}, through week ${r.latestWeek}`);
  out.push("");
  out.push(
    `Live means the ${r.liveSlots.join(", ")} captures: the prices and the projection that existed when the board was taken. ` +
      `Backfilled boards (opening, closing) are reconstructions with hindsight and are excluded. ` +
      `The Firehose takes every bettable edge of at least ${(100 * r.minEdge).toFixed(0)}% at one unit, at the best price per player and stat.`
  );

  out.push("", "## 1. Boards", "");
  if (r.boards.length === 0) out.push("No live captures yet.");
  else {
    out.push(
      table(
        ["week", "slot", "priced by", "rows", "markets", "books", "Pinnacle rows", "one-sided", "rows at the edge bar"],
        r.boards.map((b) => [
          b.week,
          b.slot,
          Object.keys(b.stats.priceModels).join("+"),
          b.stats.rows.toLocaleString(),
          b.stats.markets.toLocaleString(),
          b.stats.books,
          b.stats.pinnacleRows.toLocaleString(),
          pct(b.stats.oneSidedShare, 0).replace("+", ""),
          b.stats.edges,
        ])
      )
    );
    const odd = r.boards.filter((b) => Object.keys(b.stats.lineSources).some((s) => s !== "live"));
    if (odd.length) out.push("", `**Warning:** ${odd.map((b) => `${b.slot} week ${b.week}`).join(", ")} contain rows that are not live (${odd.map((b) => Object.keys(b.stats.lineSources).join("/")).join("; ")}). They are in the live ledger.`);
  }

  out.push("", "## 2. Pricing on live boards", "");
  const acc = r.accuracy.overall;
  if (acc.near.n === 0) out.push("No graded live markets with three or more books yet.");
  else {
    out.push("Brier score against what happened, markets within 0.25 of 50/50 by the book's price (lower is better). Gap = worse than the reference, clustered by player-week.", "");
    const row = (label, x) => [
      label,
      x.n.toLocaleString(),
      x.clusters,
      x.brierBook?.toFixed(4) ?? "–",
      x.brierProj?.toFixed(4) ?? "–",
      x.brierPool?.toFixed(4) ?? "–",
      x.projVsBook.n ? `${fx(x.projVsBook.mean)} (z ${x.projVsBook.z === null ? "–" : x.projVsBook.z.toFixed(1)})` : "–",
      x.poolVsBook.n ? `${fx(x.poolVsBook.mean)} (z ${x.poolVsBook.z === null ? "–" : x.poolVsBook.z.toFixed(1)})` : "–",
    ];
    out.push(
      table(
        ["", "markets", "player-weeks", "book", "projection", "pool", "projection − book", "pool − book"],
        [...Object.entries(r.accuracy.byWeek).map(([w, x]) => row(`week ${w}`, x.near)), row("**all weeks**", acc.near)]
      )
    );
    const thin = Object.entries(r.accuracy.byWeek).filter(([, x]) => x.near.clusters < 30).map(([w]) => w);
    if (thin.length) out.push("", `The z-scores use cluster-robust errors, which are unreliable under about 30 player-weeks (week${thin.length > 1 ? "s" : ""} ${thin.join(", ")}). Read the all-weeks row.`);
  }

  out.push("", "## 3. Bets: the Firehose, live only", "");
  if (r.betsByWeek.length === 0) out.push("No live bets yet.");
  else {
    out.push(
      table(
        ["week", "slot", "priced by", "rows at the edge bar", "bets", "settled", "pending", "ROI (±2σ)", "ROI if no-line overs lose", "CLV: beat the close"],
        [
          ...r.betsByWeek.map((b) => [b.week, b.slot, b.models, b.edgeRows ?? "–", b.summary.bets, b.summary.settled, pendingCell(b.summary), roiCell(b.summary), pct(b.summary.roiConservative), clvCell(b.summary)]),
          ["**all**", "", "", "", r.total.bets, r.total.settled, pendingCell(r.total), `**${roiCell(r.total)}**`, pct(r.total.roiConservative), clvCell(r.total)],
        ]
      )
    );
    out.push("", `Verdict on the live total: **${verdict(r.total)}**. "Rows at the edge bar" are the rows on the board that clear the minimum edge; the bets are what is left after the Firehose keeps one price per player and stat and the calibration guards (support floor, 20-point disagreement cap) are applied.`);
    if (Object.keys(r.byModel).length > 1) {
      out.push("", "By the price the board was captured under:", "");
      out.push(table(["price", "bets", "settled", "ROI (±2σ)", "CLV: beat the close"], Object.entries(r.byModel).map(([m, s]) => [m, s.bets, s.settled, roiCell(s), clvCell(s)])));
    }
  }

  out.push("", "## 3b. CLV by book", "");
  if (r.byBook.length === 0) out.push("No live bets yet.");
  else {
    out.push(
      "Where the bets came from and what their prices were worth. Each bet is taken at the best price across the books, so a book appears here when it was the best price. " +
        "**Own close** is the ledger's CLV: that book's closing price on the same line. **Market close** is the closing fair price of the *other* books on that line (at least two of them). " +
        "They can disagree: a slow book that never moves scores about zero against its own close even when its price was stale against everyone else. " +
        "† = fewer than " + MIN_CLV_FOR_A_BOOK + " measurable bets. ±2σ.",
      ""
    );
    const own = (s) => (s.clv.nMatched === 0 ? "–" : `${s.clv.nMatched} · ${(100 * s.clv.beatRate).toFixed(0)}% · ${s.clv.avgClvProb >= 0 ? "+" : ""}${(100 * s.clv.avgClvProb).toFixed(1)} pts${s.clv.nMatched < MIN_CLV_FOR_A_BOOK ? " †" : ""}`);
    const mkt = (m) => (!m || m.n === 0 ? "–" : `${m.n} · ${(100 * m.beatRate).toFixed(0)}% · ${m.avg >= 0 ? "+" : ""}${(100 * m.avg).toFixed(1)} ±${m.avgBand === null ? "?" : (100 * m.avgBand).toFixed(1)} pts${m.n < MIN_CLV_FOR_A_BOOK ? " †" : ""}`);
    out.push(
      table(
        ["book", "bets", "settled", "ROI (±2σ)", "own close: measurable · beat · avg", "market close: measurable · beat · avg"],
        r.byBook.map((b) => [b.label, b.summary.bets, b.summary.settled, roiCell(b.summary), own(b.summary), mkt(b.market)])
      )
    );
    const nBooks = r.byBook.length;
    const noMarket = r.byBook.reduce((a, b) => a + b.summary.bets - (b.market?.n ?? 0), 0);
    out.push("", `${nBooks} book${nBooks === 1 ? "" : "s"}. ${noMarket} of ${r.total.bets} bets have no market close: fewer than two other books quoted that exact line at the close, which is common for the one-sided alternate lines the slow books post.`);
  }

  out.push("", "## 4. The same live boards under the other price", "");
  if (!r.counterfactual) out.push("Not run.");
  else {
    const cf = r.counterfactual;
    out.push(
      "Each live board re-priced under the model it was *not* captured under and run through the same persona engine: boards captured on the projection price with the pool as it would have stood that week (weights fitted on earlier weeks), and boards captured on the pool with the projection price. The two directions are separate questions and are not added together.",
      ""
    );
    const rowsCf = [];
    for (const [dir, d] of Object.entries(cf.directions)) {
      const from = dir === "pool" ? "projection" : "pool";
      rowsCf.push([`${from}-priced boards (${d.boards.length}): as captured`, d.asCaptured.bets, d.asCaptured.settled, pendingCell(d.asCaptured), roiCell(d.asCaptured), clvCell(d.asCaptured)]);
      rowsCf.push([`… re-priced with the ${dir}`, d.other.bets, d.other.settled, pendingCell(d.other), roiCell(d.other), clvCell(d.other)]);
    }
    out.push(table(["", "bets", "settled", "pending", "ROI (±2σ)", "CLV: beat the close"], rowsCf));
    out.push("", "Boards: " + Object.entries(cf.directions).map(([dir, d]) => `${d.boards.join(", ")} (${dir === "pool" ? "projection" : "pool"} → ${dir})`).join("; ") + ".");
  }

  out.push("", "## 5. Every persona, live only", "");
  out.push(table(["persona", "bets", "settled", "pending", "ROI (±2σ)", "CLV: beat the close"], r.personas.map((p) => [p.label, p.summary.bets, p.summary.settled, pendingCell(p.summary), roiCell(p.summary), clvCell(p.summary)])));

  out.push("", "## 6. Can you read it?", "");
  const t = r.total;
  const need = t.roi !== null ? betsToResolve(t.roi, t.perBetSd) : null;
  const need5 = t.perBetSd ? betsToResolve(0.05, t.perBetSd) : null;
  const liveWeeks = new Set(r.betsByWeek.filter((b) => b.summary.settled > 0).map((b) => b.week)).size;
  const perWeek = liveWeeks > 0 ? t.settled / liveWeeks : null;
  const weeksFor = (n) => (perWeek ? Math.ceil((n - t.settled) / perWeek) : null);
  out.push(
    `- **Settled live bets: ${t.settled}.** A verdict needs at least ${MIN_BETS_FOR_A_VERDICT}, and the per-bet spread is ${t.perBetSd ? t.perBetSd.toFixed(2) : "–"} units.`,
    need !== null ? `- Seeing an ROI of ${pct(t.roi)} at two sigma takes about ${need.toLocaleString()} settled bets; you have ${t.settled}.` : "- No ROI to resolve yet.",
    need5 !== null
      ? `- Seeing a **5%** ROI takes about ${need5.toLocaleString()} settled bets. At the current ${perWeek ? perWeek.toFixed(0) : "–"} settled a week that is about ${weeksFor(need5) ?? "–"} more weeks — longer than a season.`
      : "",
    "- CLV resolves far faster than ROI because it is a price difference, not a coin flip, but it is partly mechanical: a slow book's off-market price stays off-market until the close.",
    "- Pending bets in finished weeks have no stat line. For an over that is almost always a loss the settlement cannot see; the conservative column counts them.",
    "- Bets on one player are correlated, so the bands are if anything too narrow."
  );
  return out.filter((l) => l !== "").length ? out.join("\n").replace(/\n{3,}/g, "\n\n") : "";
}

try {
  main();
} catch (err) {
  console.error(`backtest-live: ${err.stack ?? err.message}`);
  process.exitCode = 1;
}
